apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: netflix-clone

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml


# - route.yaml

commonLabels:
  app: netflix-clone
